# Generated by Django 4.2.3 on 2023-07-07 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('career_obj', models.CharField(max_length=500)),
                ('contact_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('github_profile', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='StrengthsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(max_length=200)),
                ('person_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('person_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SeminarsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semimar_attended', models.CharField(max_length=200)),
                ('person_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('date_period', models.CharField(max_length=20)),
                ('person_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CharReferencesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_ref_name', models.CharField(max_length=80)),
                ('ref_email', models.EmailField(max_length=254)),
                ('ref_contact_no', models.CharField(max_length=11)),
                ('person_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.generalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=200)),
                ('person_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.generalinfo')),
            ],
        ),
    ]
